<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DeltaDiagnostics.AotSmoke</AssemblyName>
    <RootNamespace>Delta.Diagnostics.AotSmoke</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NuGetAudit>false</NuGetAudit>
    <PublishAot Condition="'$(AotSmoke)' == 'true'">true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DeltaDiagnostics.Contract/Delta.Diagnostics.Contract.csproj" />
  </ItemGroup>
</Project>
